name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v3		
      - name: Fetch Alumni Data üì¶
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://script.google.com/macros/s/AKfycby04N7LotTrhxNZ8wMPRW9Pskoo2bRt4HnQ3NwECHGpNK1V3Ywg/exec
          configuration: '{ "method": "GET"}'
          save-location: dist
          save-name: alumni
      - name: Fetch Accounts Data üì¶
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://script.google.com/macros/s/AKfycbzGS-NsFvOXmnWs_SCm16ccWJyiXiYEnsTh5ZV3jbCuvELsYIMD/exec
          configuration: '{ "method": "GET"}'
          save-location: dist
          save-name: accounts
      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
